apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV5TVRFeQpNVEUxTkROYUZ3MDBNakV5TVRFeU1URTFORE5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEaW5RNnRqRG94WThRWUlUSzdtL0FPV2R3S1lKWmZvSzRKTkwxUzZoaDZkc25vTU9hWQpROU00UkgzejB0TUFUcE14ckFCZU5tMGRJNlBGRlpKVjMxWEpoaVAwT29iK1FpT2QvSk41c0FPRnowcGh6dTN3ClpXVEd5MHlib0M4YkcyYkRLWnlxNDlpK3ZRS0w0a2YxdUM5OU9jNUJ6akhKdTdMdEtxWjMyblpvbjJDL1FnMXoKRXRXcmhxQnA4ZU82TkxsYUl5cUpKU1lBeHBRNTUzbnpteVNaRTA0TGlwNEdJbDlxQzNEU3pRRUVBNHV0ZWdmSgpTcU83ZWlhN2JjbHY1MGJzZTRJYis0aTVVSWFrV2lEYkFtZTNYUWVTMXFicE0wZWRRakdxaEtIcjh4dUFJdDhxCnY5OG1KTG04N2Y0VXN1aUpQWUs3a0ptcm13V3E4dnp5V29hOUFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJLYmFrdFF2SDFOQnlCZnVaTQpBNU0yM2dUNU96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFiOW5mVHVPNTB1ZmdLeE82d2t6bWRMUE0wR0VNCjNWYThmRVB0Y3pjZmVsRXUvc0kvRCtCMitXaGdHeDIwb0dCc3FUQkpjeUlVL2ppVXRnc1BpOXN2a3ZkdVpCTmcKTEltazI2SkQ5cWdKTFU3ZlYybXFLNzVWMUliZGhVVkRmeUdRazRwUndOV0xReEFrc2hXdjFJc0lURmhxQUprSQpxbUhKbWJ6blR5SlJweEtMK1NGL2tnTXp5YURZUUlhUks1WHVERFI0RFNYMVBwekJBMGFhYXIrL2R0UkR0UXpkCmxvc1UzYlBVTHRwczFLRnBpUE1jeTYxNnBTNnJKK1Z3bmtqUloxTndUaFhwdWRXeUt1c0c1WU1GZVdtcDhQTVAKRThIVFEwVjgveGxJRjdyZ1pkdTlSMEZBVVRzVDdWZm1KKy90M2VVMU12VktzMWxqQUN5enMzdlByZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://06d1d558-bb4a-41c8-b312-1d104030aad3.k8s.ondigitalocean.com
  name: do-nyc3-carfax
contexts:
- context:
    cluster: do-nyc3-carfax
    user: do-nyc3-carfax-admin
  name: do-nyc3-carfax
current-context: do-nyc3-carfax
kind: Config
preferences: {}
users:
- name: do-nyc3-carfax-admin
  user:
    token: dop_v1_87e1401a3e1c01cb2b19bd33eb74c4128db9611285f9b330e7c0f370dd52b0b7
